//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Mememorphosis
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const mememorphosisABI = [
  {
    stateMutability: 'nonpayable',
    type: 'constructor',
    inputs: [
      { name: 'minGasToStore', internalType: 'uint256', type: 'uint256' },
      { name: 'defaultGasLimit', internalType: 'uint256', type: 'uint256' },
      { name: 'layerZeroEndpoint', internalType: 'address', type: 'address' },
      { name: 'startMintId', internalType: 'uint256', type: 'uint256' },
      { name: 'endMintId', internalType: 'uint256', type: 'uint256' },
      { name: 'mintPrice_', internalType: 'uint256', type: 'uint256' },
      { name: 'sendPrice_', internalType: 'uint256', type: 'uint256' },
      { name: 'chainId', internalType: 'uint8', type: 'uint8' },
    ],
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'approved',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'tokenId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
    ],
    name: 'Approval',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'operator',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      { name: 'approved', internalType: 'bool', type: 'bool', indexed: false },
    ],
    name: 'ApprovalForAll',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: '_hashedPayload',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: false,
      },
    ],
    name: 'CreditCleared',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: '_hashedPayload',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: false,
      },
      {
        name: '_payload',
        internalType: 'bytes',
        type: 'bytes',
        indexed: false,
      },
    ],
    name: 'CreditStored',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: '_srcChainId',
        internalType: 'uint16',
        type: 'uint16',
        indexed: false,
      },
      {
        name: '_srcAddress',
        internalType: 'bytes',
        type: 'bytes',
        indexed: false,
      },
      {
        name: '_nonce',
        internalType: 'uint64',
        type: 'uint64',
        indexed: false,
      },
      {
        name: '_payload',
        internalType: 'bytes',
        type: 'bytes',
        indexed: false,
      },
      { name: '_reason', internalType: 'bytes', type: 'bytes', indexed: false },
    ],
    name: 'MessageFailed',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'previousOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'newOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'OwnershipTransferred',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: '_srcChainId',
        internalType: 'uint16',
        type: 'uint16',
        indexed: true,
      },
      {
        name: '_srcAddress',
        internalType: 'bytes',
        type: 'bytes',
        indexed: true,
      },
      {
        name: '_toAddress',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: '_tokenIds',
        internalType: 'uint256[]',
        type: 'uint256[]',
        indexed: false,
      },
    ],
    name: 'ReceiveFromChain',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'referrer',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'referral',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
    ],
    name: 'Referral',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: '_srcChainId',
        internalType: 'uint16',
        type: 'uint16',
        indexed: false,
      },
      {
        name: '_srcAddress',
        internalType: 'bytes',
        type: 'bytes',
        indexed: false,
      },
      {
        name: '_nonce',
        internalType: 'uint64',
        type: 'uint64',
        indexed: false,
      },
      {
        name: '_payloadHash',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: false,
      },
    ],
    name: 'RetryMessageSuccess',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: '_dstChainId',
        internalType: 'uint16',
        type: 'uint16',
        indexed: true,
      },
      {
        name: '_from',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: '_toAddress',
        internalType: 'bytes',
        type: 'bytes',
        indexed: true,
      },
      {
        name: '_tokenIds',
        internalType: 'uint256[]',
        type: 'uint256[]',
        indexed: false,
      },
    ],
    name: 'SendToChain',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: '_dstChainId',
        internalType: 'uint16',
        type: 'uint16',
        indexed: false,
      },
      {
        name: '_dstChainIdToBatchLimit',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'SetDstChainIdToBatchLimit',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: '_dstChainId',
        internalType: 'uint16',
        type: 'uint16',
        indexed: false,
      },
      {
        name: '_dstChainIdToTransferGas',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'SetDstChainIdToTransferGas',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: '_dstChainId',
        internalType: 'uint16',
        type: 'uint16',
        indexed: false,
      },
      { name: '_type', internalType: 'uint16', type: 'uint16', indexed: false },
      {
        name: '_minDstGas',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'SetMinDstGas',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: '_minGasToTransferAndStore',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'SetMinGasToTransferAndStore',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'precrime',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
    ],
    name: 'SetPrecrime',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: '_remoteChainId',
        internalType: 'uint16',
        type: 'uint16',
        indexed: false,
      },
      { name: '_path', internalType: 'bytes', type: 'bytes', indexed: false },
    ],
    name: 'SetTrustedRemote',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: '_remoteChainId',
        internalType: 'uint16',
        type: 'uint16',
        indexed: false,
      },
      {
        name: '_remoteAddress',
        internalType: 'bytes',
        type: 'bytes',
        indexed: false,
      },
    ],
    name: 'SetTrustedRemoteAddress',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'from', internalType: 'address', type: 'address', indexed: true },
      { name: 'to', internalType: 'address', type: 'address', indexed: true },
      {
        name: 'tokenId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
    ],
    name: 'Transfer',
  },
  { stateMutability: 'payable', type: 'fallback' },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'DEFAULT_PAYLOAD_SIZE_LIMIT',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'FUNCTION_TYPE_SEND',
    outputs: [{ name: '', internalType: 'uint16', type: 'uint16' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'tokenId', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'approve',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'owner', internalType: 'address', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [],
    name: 'claimFunds',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_payload', internalType: 'bytes', type: 'bytes' }],
    name: 'clearCredits',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '', internalType: 'uint16', type: 'uint16' }],
    name: 'dstChainIdToBatchLimit',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '', internalType: 'uint16', type: 'uint16' }],
    name: 'dstChainIdToTransferGas',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: '_dstChainId', internalType: 'uint16', type: 'uint16' },
      { name: '_toAddress', internalType: 'bytes', type: 'bytes' },
      { name: '_tokenIds', internalType: 'uint256[]', type: 'uint256[]' },
      { name: '_useZro', internalType: 'bool', type: 'bool' },
      { name: '_adapterParams', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'estimateSendBatchFee',
    outputs: [
      { name: 'nativeFee', internalType: 'uint256', type: 'uint256' },
      { name: 'zroFee', internalType: 'uint256', type: 'uint256' },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: '_dstChainId', internalType: 'uint16', type: 'uint16' },
      { name: '_toAddress', internalType: 'bytes', type: 'bytes' },
      { name: '_tokenId', internalType: 'uint256', type: 'uint256' },
      { name: '_useZro', internalType: 'bool', type: 'bool' },
      { name: '_adapterParams', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'estimateSendFee',
    outputs: [
      { name: 'nativeFee', internalType: 'uint256', type: 'uint256' },
      { name: 'zroFee', internalType: 'uint256', type: 'uint256' },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: '', internalType: 'uint16', type: 'uint16' },
      { name: '', internalType: 'bytes', type: 'bytes' },
      { name: '', internalType: 'uint64', type: 'uint64' },
    ],
    name: 'failedMessages',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_srcChainId', internalType: 'uint16', type: 'uint16' },
      { name: '_srcAddress', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'forceResumeReceive',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'tokenId', internalType: 'uint256', type: 'uint256' }],
    name: 'getApproved',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: '_version', internalType: 'uint16', type: 'uint16' },
      { name: '_chainId', internalType: 'uint16', type: 'uint16' },
      { name: '', internalType: 'address', type: 'address' },
      { name: '_configType', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'getConfig',
    outputs: [{ name: '', internalType: 'bytes', type: 'bytes' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: '_remoteChainId', internalType: 'uint16', type: 'uint16' },
    ],
    name: 'getTrustedRemoteAddress',
    outputs: [{ name: '', internalType: 'bytes', type: 'bytes' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'id', internalType: 'uint256', type: 'uint256' }],
    name: 'getVisitedChains',
    outputs: [
      { name: 'visitedChains', internalType: 'uint8[]', type: 'uint8[]' },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: 'owner', internalType: 'address', type: 'address' },
      { name: 'operator', internalType: 'address', type: 'address' },
    ],
    name: 'isApprovedForAll',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: '_srcChainId', internalType: 'uint16', type: 'uint16' },
      { name: '_srcAddress', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'isTrustedRemote',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'lzEndpoint',
    outputs: [
      {
        name: '',
        internalType: 'contract ILayerZeroEndpoint',
        type: 'address',
      },
    ],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_srcChainId', internalType: 'uint16', type: 'uint16' },
      { name: '_srcAddress', internalType: 'bytes', type: 'bytes' },
      { name: '_nonce', internalType: 'uint64', type: 'uint64' },
      { name: '_payload', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'lzReceive',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'maxMintId',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'metadataGenerator',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: '', internalType: 'uint16', type: 'uint16' },
      { name: '', internalType: 'uint16', type: 'uint16' },
    ],
    name: 'minDstGasLookup',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'minGasToTransferAndStore',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'payable',
    type: 'function',
    inputs: [{ name: 'n', internalType: 'uint256', type: 'uint256' }],
    name: 'mint',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'mintPrice',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'payable',
    type: 'function',
    inputs: [
      { name: 'n', internalType: 'uint256', type: 'uint256' },
      { name: 'referrer', internalType: 'address', type: 'address' },
    ],
    name: 'mintWithReferral',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'name',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'nextMintId',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_srcChainId', internalType: 'uint16', type: 'uint16' },
      { name: '_srcAddress', internalType: 'bytes', type: 'bytes' },
      { name: '_nonce', internalType: 'uint64', type: 'uint64' },
      { name: '_payload', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'nonblockingLzReceive',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'owner',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'tokenId', internalType: 'uint256', type: 'uint256' }],
    name: 'ownerOf',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '', internalType: 'uint16', type: 'uint16' }],
    name: 'payloadSizeLimitLookup',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'precrime',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
  },
  {
    stateMutability: 'payable',
    type: 'function',
    inputs: [
      { name: '_srcChainId', internalType: 'uint16', type: 'uint16' },
      { name: '_srcAddress', internalType: 'bytes', type: 'bytes' },
      { name: '_nonce', internalType: 'uint64', type: 'uint64' },
      { name: '_payload', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'retryMessage',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'from', internalType: 'address', type: 'address' },
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'tokenId', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'safeTransferFrom',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'from', internalType: 'address', type: 'address' },
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'tokenId', internalType: 'uint256', type: 'uint256' },
      { name: 'data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'safeTransferFrom',
    outputs: [],
  },
  {
    stateMutability: 'payable',
    type: 'function',
    inputs: [
      { name: '_from', internalType: 'address', type: 'address' },
      { name: '_dstChainId', internalType: 'uint16', type: 'uint16' },
      { name: '_toAddress', internalType: 'bytes', type: 'bytes' },
      { name: '_tokenIds', internalType: 'uint256[]', type: 'uint256[]' },
      {
        name: '_refundAddress',
        internalType: 'address payable',
        type: 'address',
      },
      { name: '_zroPaymentAddress', internalType: 'address', type: 'address' },
      { name: '_adapterParams', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'sendBatchFrom',
    outputs: [],
  },
  {
    stateMutability: 'payable',
    type: 'function',
    inputs: [
      { name: '_from', internalType: 'address', type: 'address' },
      { name: '_dstChainId', internalType: 'uint16', type: 'uint16' },
      { name: '_toAddress', internalType: 'bytes', type: 'bytes' },
      { name: '_tokenId', internalType: 'uint256', type: 'uint256' },
      {
        name: '_refundAddress',
        internalType: 'address payable',
        type: 'address',
      },
      { name: '_zroPaymentAddress', internalType: 'address', type: 'address' },
      { name: '_adapterParams', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'sendFrom',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'sendPrice',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'operator', internalType: 'address', type: 'address' },
      { name: 'approved', internalType: 'bool', type: 'bool' },
    ],
    name: 'setApprovalForAll',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_version', internalType: 'uint16', type: 'uint16' },
      { name: '_chainId', internalType: 'uint16', type: 'uint16' },
      { name: '_configType', internalType: 'uint256', type: 'uint256' },
      { name: '_config', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'setConfig',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_dstChainId', internalType: 'uint16', type: 'uint16' },
      {
        name: '_dstChainIdToBatchLimit',
        internalType: 'uint256',
        type: 'uint256',
      },
    ],
    name: 'setDstChainIdToBatchLimit',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_dstChainId', internalType: 'uint16', type: 'uint16' },
      {
        name: '_dstChainIdToTransferGas',
        internalType: 'uint256',
        type: 'uint256',
      },
    ],
    name: 'setDstChainIdToTransferGas',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'metadataGenerator_', internalType: 'address', type: 'address' },
    ],
    name: 'setMetadataGenerator',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_dstChainId', internalType: 'uint16', type: 'uint16' },
      { name: '_packetType', internalType: 'uint16', type: 'uint16' },
      { name: '_minGas', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'setMinDstGas',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {
        name: '_minGasToTransferAndStore',
        internalType: 'uint256',
        type: 'uint256',
      },
    ],
    name: 'setMinGasToTransferAndStore',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'mintPrice_', internalType: 'uint256', type: 'uint256' }],
    name: 'setMintPrice',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_dstChainId', internalType: 'uint16', type: 'uint16' },
      { name: '_size', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'setPayloadSizeLimit',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_precrime', internalType: 'address', type: 'address' }],
    name: 'setPrecrime',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_version', internalType: 'uint16', type: 'uint16' }],
    name: 'setReceiveVersion',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'sendPrice_', internalType: 'uint256', type: 'uint256' }],
    name: 'setSendPrice',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_version', internalType: 'uint16', type: 'uint16' }],
    name: 'setSendVersion',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_remoteChainId', internalType: 'uint16', type: 'uint16' },
      { name: '_path', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'setTrustedRemote',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_remoteChainId', internalType: 'uint16', type: 'uint16' },
      { name: '_remoteAddress', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'setTrustedRemoteAddress',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
    name: 'storedCredits',
    outputs: [
      { name: 'srcChainId', internalType: 'uint16', type: 'uint16' },
      { name: 'toAddress', internalType: 'address', type: 'address' },
      { name: 'index', internalType: 'uint256', type: 'uint256' },
      { name: 'creditsRemain', internalType: 'bool', type: 'bool' },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'interfaceId', internalType: 'bytes4', type: 'bytes4' }],
    name: 'supportsInterface',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'symbol',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'index', internalType: 'uint256', type: 'uint256' }],
    name: 'tokenByIndex',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: 'owner', internalType: 'address', type: 'address' },
      { name: 'index', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'tokenOfOwnerByIndex',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'tokenId', internalType: 'uint256', type: 'uint256' }],
    name: 'tokenURI',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'totalSupply',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'from', internalType: 'address', type: 'address' },
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'tokenId', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'transferFrom',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'newOwner', internalType: 'address', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '', internalType: 'uint16', type: 'uint16' }],
    name: 'trustedRemoteLookup',
    outputs: [{ name: '', internalType: 'bytes', type: 'bytes' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    name: 'visitedChainsMask',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  { stateMutability: 'payable', type: 'receive' },
] as const

export const mememorphosisAddress =
  '0x0000049F63Ef0D60aBE49fdD8BEbfa5a68822222' as const

export const mememorphosisConfig = {
  address: mememorphosisAddress,
  abi: mememorphosisABI,
} as const
